# Generated by Django 4.2.4 on 2023-08-24 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='user',
        ),
        migrations.AlterField(
            model_name='stage',
            name='status',
            field=models.TextField(default='idle', max_length=20),
        ),
    ]
